[package]
name = "buddy-allocator-nightly"
version = "0.1.0"
edition = "2021"

[dependencies]

# Allow cargo fmt and cargo test for all specified dependencies.
# cargo fmt
# cargo test --workspace
[workspace]
members = []

[features]
no-std = []
no-generic-std-mutex-impl = []

[dev-dependencies]